2019-08-05 21:23:16 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 253, in async_step_pair
    self.finish_pairing, code
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller/controller.py", line 385, in finish_pairing
    Controller.check_pin_format(pin)
  File "/usr/local/lib/python3.7/site-packages/homekit/controller/controller.py", line 312, in check_pin_format
    raise MalformedPinError('The pin must be of the following XXX-XX-XXX where X is a digit between 0 and 9.')
homekit.exceptions.MalformedPinError: The pin must be of the following XXX-XX-XXX where X is a digit between 0 and 9.
2019-08-05 21:33:21 WARNING (zeroconf-ServiceBrowser__googlecast._tcp.local.) [zeroconf] Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 2245, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
PermissionError: [Errno 1] Operation not permitted
2019-08-05 21:33:21 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: light.cuisine. Platform hue does not generate unique IDs
2019-08-05 21:41:18 WARNING (Thread-3) [pychromecast.socket_client] [Google Salon:8009] Heartbeat timeout, resetting connection
2019-08-05 21:41:20 WARNING (Thread-2) [pychromecast.socket_client] [Chambre:8009] Heartbeat timeout, resetting connection
2019-08-05 22:00:49 WARNING (Thread-3) [pychromecast.socket_client] [Google Salon:8009] Heartbeat timeout, resetting connection
2019-08-05 22:00:56 WARNING (Thread-2) [pychromecast.socket_client] [Chambre:8009] Heartbeat timeout, resetting connection
2019-08-05 22:01:41 ERROR (Thread-3) [pychromecast.socket_client] [Google Salon:8009] Failed to connect to service Google-Home-7b9202500de1dd542150952eb0dcf20d._googlecast._tcp.local., retrying in 5.0s
2019-08-05 22:01:41 ERROR (Thread-2) [pychromecast.socket_client] [Chambre:8009] Failed to connect to service Google-Home-Mini-04bc391cda9a3f9bb2982d0c4c58447c._googlecast._tcp.local., retrying in 5.0s
2019-08-05 23:54:29 WARNING (Thread-4) [pychromecast.socket_client] [ChromSalon:8009] Heartbeat timeout, resetting connection
2019-08-05 23:55:00 ERROR (Thread-4) [pychromecast.socket_client] [ChromSalon:8009] Failed to connect to service Chromecast-0f426f8e3f11637c2a954a766457484c._googlecast._tcp.local., retrying in 5.0s
2019-08-06 02:04:28 WARNING (Thread-2) [pychromecast.socket_client] [Chambre:8009] Heartbeat timeout, resetting connection
2019-08-06 03:46:34 WARNING (Thread-3) [pychromecast.socket_client] [Google Salon:8009] Heartbeat timeout, resetting connection
2019-08-06 08:59:17 WARNING (Thread-4) [pychromecast.socket_client] [ChromSalon:8009] Heartbeat timeout, resetting connection
2019-08-06 08:59:47 ERROR (Thread-4) [pychromecast.socket_client] [ChromSalon:8009] Failed to connect to service Chromecast-0f426f8e3f11637c2a954a766457484c._googlecast._tcp.local., retrying in 5.0s
2019-08-06 10:41:27 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.2.102
2019-08-06 10:41:27 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.2.102
2019-08-06 11:52:38 ERROR (SyncWorker_16) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-08-06 11:52:43 ERROR (SyncWorker_16) [homeassistant.components.recorder.util] Error executing query: (sqlite3.OperationalError) database is locked
(Background on this error at: http://sqlalche.me/e/e3q8)
